use_frameworks!

target 'AKWeiboManager_Example' do
  pod 'AKWeiboManager', :path => '../'
  
  pod 'AKWeiboSDK', :git => 'git@github.com:ArtisanKid/AKWeiboSDK.git'
  #pod 'AKWeiboSDK', :path => '../../AKWeiboSDK'
  
  pre_install do |installer|
      # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
      def installer.verify_no_static_framework_transitive_dependencies; end
  end

  target 'AKWeiboManager_Tests' do
    inherit! :search_paths

    
  end
end
